{% set name = "methylmap" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3df13ed049541db2c228f3859542786b3989cfcb511af831bad772be01805f5

build:
  number: 0
  entry_points:
    - methylmap=methylmap.methylmap:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.14.3
    - pandas >=0.23.4
    - plotly >=5.4.0
    - pyranges >=0.0.77
    - tabix
    - modbam2bed

test:
  imports:
    - methylmap
  commands:
    - methylmap --help

about:
  home: https://github.com/EliseCoopman/methylmap
  license: MIT
  license_family: MIT
  summary: Plotting tool for population scale nucleotide modifications

extra:
  recipe-maintainers:
    - EliseCoopman